export default {
    cannotFind: "해당 게시물을 불러올 수 없습니다.",
    toList: "목록으로",
    edit: "수정",
    history: "역사",
    delete: "지우기",
    archive: "보관",
    timeFormat: 'M월 D일 hh:mm',
    replying: '댓글 다는 중..',
    reply: '댓글 달기',
    whatOpinion: '어떤 의견을 갖고 계신가요?',
    commentList: '댓글 목록',
    archiveDocument: '문서 보관',
    archiveDocumentWarning: '문서를 정말 보관하시겠습니까?',
    deleteComment: '댓글 삭제',
    deleteCommentWarning: '댓글을 정말 삭제하시겠습니까?',
    commentGroup: '댓글 타래',
    more: '더 보기...',
    documentContent: '본문 내용'
};